name: uas_pemrogramanbergerak
description: "Don't Get Blown Up - Dodge the rockets!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.18.0
  #web: ^0.5.1
  flame_audio: ^2.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/button_next.png
    - assets/images/panel.png
    - assets/images/button_next.png
    - assets/images/button_previous.png
    - assets/images/howtoplay.png 
    - assets/images/jet_atasbawah.png
    - assets/images/button_play.png
    - assets/images/button_playagain.png
    - assets/images/explossion.png
    - assets/images/health_fuel.png
    - assets/images/button_tutorial.png
    - assets/images/jet.png
    - assets/images/logo_game.png
    - assets/images/game_over.png
    - assets/images/rocket1.png
    - assets/images/rocket2.png
    - assets/images/rocket3.png
    - assets/images/text_health.png
    - assets/images/text_score.png
    - assets/audio/bgm.mp3
    - assets/audio/meledak.mp3
    - assets/audio/roket.mp3

# Tambahkan ini di baris paling bawah
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_game.png" # Path menuju gambar ikonmu
  # Jika ingin *background* ikon transparan diisi warna, bisa tambah:
  # adaptive_icon_background: "#000000"